version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dumpsterAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3pshm7by1h95"
s3_prefix = "dumpsterAPI"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
